### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by dalduba** [WellerQu/rete-selection-plugin#1]
Hello!. I connected this plugin but my area is moving  when I drag my mouse.
I have the folloowing plugins in my editor:
rete-context-menu-plugin
rete-area-plugin
rete-history-plugin
rete-connection-path-plugin
rete-selection-plugin
rete-keyboard-plugin

Could you help please?

**Comment by usbdem** [comment]
@dalduba CTRL + mouse start select

**Comment by dalduba** [comment]
> @dalduba CTRL + mouse start select

I see the rect but the area is still drags with all nodes

**Comment by WellerQu** [comment]
first, we can NOT select anyone node
then, we can press ctrl + mouse to select an area

if this plugin does not work, could you provide an example, such as codesandbox? @dalduba
